# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Olympia	
tagline:          'A Python Blog.'
description:      'Posts about programming in Python, especially Flask by <a href="https://github.com/hassaanaliw">@hassaanaliw</a>'
url:              http://hassaanaliw.github.io
baseurl:          /

author:
  name:           'Hassaan Ali Wattoo'
  url:            https://github.com/hassaanaliw

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hassaanaliw/hassaanaliw.github.io
