# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Olympia
tagline:          'A Programming Blog'
description:      'Python and Java challenges and tutorials'
url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5

author:
  name:           'Hassaan Ali Wattoo'
  url:            https://github.com/hassaanaliw

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hassaanaliw/hassaanaliw.github.io
