name: Olympia
description: Blogging about Python and Flask.
meta_description: "Your Pythonic blog to all things Flask."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://hassaanaliw.me'
google_analytics: 'UA-54672427-1'

# Details for the RSS feed generator
url:            'http://hassaanaliw.me'
author:         'Hassaan Ali Wattoo'
